Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 42, in post
    logger.error(f"登录失败: {form.errors}")
NameError: name 'logger' is not defined
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 42, in post
    logger.error(f"登录失败: {form.errors}")
NameError: name 'logger' is not defined
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Not Found: /favicon.ico
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Watching for file changes with StatReloader
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=entertainment
认证失败: login_field=entertainment
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=654
认证失败: login_field=654
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Watching for file changes with StatReloader
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
尝试认证: login_field=ent
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 38, in post
    if form.is_valid():
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\forms\forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\forms\forms.py", line 200, in errors
    self.full_clean()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\forms\forms.py", line 438, in full_clean
    self._clean_form()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\forms\forms.py", line 459, in _clean_form
    cleaned_data = self.clean()
  File "Z:\desk\code\hardware_analyzer\accounts\forms.py", line 65, in clean
    user = authenticate(request=self.request, login_field=login_field, password=password)
AttributeError: 'CustomAuthenticationForm' object has no attribute 'request'
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=15631128911
认证失败: login_field=15631128911
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Unauthorized: /api/favorites/
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Price history for cpu/4: 10 records
Price history for cpu/9: 2 records
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配forms</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配forms</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配forms</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配forms</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证失败: login_field=ent
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\__init__.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Price history for cpu/2: 17 records
Unauthorized: /api/favorites/
Price history for motherboard/1: 0 records
Unauthorized: /api/favorite/
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Price history for motherboard/1: 0 records
Price history for motherboard/2: 0 records
Price history for motherboard/5: 0 records
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Watching for file changes with StatReloader
Price history for ram/1: 0 records
Price history for ram/6: 0 records
Price history for ram/1: 0 records
Price history for ram/9: 0 records
Price history for cpu/7: 0 records
Price history for cpu/6: 10 records
Price history for ram/1: 0 records
Price history for ram/7: 0 records
Price history for ram/9: 0 records
Price history for ram/10: 0 records
Not Found: /favicon.ico
Price history for ram/1: 0 records
Price history for motherboard/1: 0 records
Price history for ram/4: 0 records
Price history for ram/1: 0 records
Price history for ram/10: 0 records
Price history for ram/18: 0 records
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Price history for ram/1: 0 records
Price history for ram/2: 0 records
Price history for ram/7: 0 records
Price history for ram/1: 0 records
Internal Server Error: /api/detail/gpu/1/
Price history for ram/1: 0 records
Price history for ram/6: 4 records
Price history for ram/8: 0 records
Price history for ram/10: 1 records
Price history for ram/17: 0 records
Price history for ram/14: 2 records
Price history for ram/19: 0 records
Price history for ram/20: 0 records
Price history for cpu/1: 4 records
Price history for cpu/7: 0 records
Price history for cpu/9: 2 records
Price history for cpu/10: 3 records
Price history for cpu/5: 1 records
Price history for cpu/29: 8 records
Price history for cpu/28: 0 records
Price history for cpu/25: 0 records
Price history for cpu/30: 0 records
Price history for cpu/24: 8 records
Price history for cpu/21: 9 records
Price history for cpu/22: 3 records
Price history for ram/1: 0 records
Price history for ram/59: 0 records
Price history for ram/109: 0 records
Price history for ram/110: 1 records
Price history for ram/118: 0 records
Price history for ram/118: 0 records
Price history for ram/116: 0 records
Price history for ram/130: 7 records
Price history for ram/140: 0 records
Price history for ram/167: 7 records
Price history for ram/170: 2 records
Price history for ram/168: 10 records
Price history for ram/168: 10 records
Price history for ram/167: 7 records
Price history for cpu/29: 8 records
Price history for cpu/21: 9 records
Price history for cpu/22: 3 records
Price history for ram/168: 10 records
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Price history for ram/1: 0 records
Internal Server Error: /api/detail/gpu/1/
Price history for cpu/1: 4 records
Price history for cpu/7: 0 records
Price history for cpu/9: 2 records
Price history for cpu/10: 3 records
Watching for file changes with StatReloader
Price history for cpu/9: 2 records
Price history for cpu/24: 8 records
Price history for cpu/7: 0 records
Price history for cpu/3: 10 records
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Unauthorized: /api/favorites/
Unauthorized: /api/favorites/
Price history for cpu/3: 10 records
Price history for cpu/1: 4 records
Price history for ram/7: 0 records
Internal Server Error: /api/detail/gpu/5/
Internal Server Error: /api/detail/power_supply/1/
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 216, in get
    context = self.get_context_data(**kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 127, in get_context_data
    alerts = PriceAlert.objects.filter(user=self.request.user, is_active=True)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_active' into field. Choices are: current_price, favorite, favorite_id, id, is_read, method, previous_price, sent_at, user, user_id
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 216, in get
    context = self.get_context_data(**kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 127, in get_context_data
    alerts = PriceAlert.objects.filter(user=self.request.user, is_active=True)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_active' into field. Choices are: current_price, favorite, favorite_id, id, is_read, method, previous_price, sent_at, user, user_id
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 216, in get
    context = self.get_context_data(**kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 129, in get_context_data
    alerts = PriceAlert.objects.filter(user=self.request.user, is_active=True)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_active' into field. Choices are: current_price, favorite, favorite_id, id, is_read, method, previous_price, sent_at, user, user_id
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 216, in get
    context = self.get_context_data(**kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 129, in get_context_data
    alerts = PriceAlert.objects.filter(user=self.request.user, is_active=True)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_active' into field. Choices are: current_price, favorite, favorite_id, id, is_read, method, previous_price, sent_at, user, user_id
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\generic\base.py", line 216, in get
    context = self.get_context_data(**kwargs)
  File "Z:\desk\code\hardware_analyzer\accounts\views.py", line 129, in get_context_data
    alerts = PriceAlert.objects.filter(user=self.request.user, is_active=True)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_active' into field. Choices are: current_price, favorite, favorite_id, id, is_read, method, previous_price, sent_at, user, user_id
Z:\desk\code\hardware_analyzer\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def check_price_changes():
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def check_price_changes():
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def check_price_changes():
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Price history for ram/168: 10 records
Price history for ram/168: 10 records
Price history for cpu/4: 10 records
Price history for cpu/3: 10 records
Price history for cpu/3: 10 records
Price history for cpu/3: 10 records
Price history for cpu/3: 10 records
Not Found: /favicon.ico
Price history for cpu/3: 10 records
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
尝试认证: login_field=ent
认证成功: 用户 ent
用户 ent 登录成功
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def check_price_changes():
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

尝试认证: login_field=testuser
认证成功: 用户 testuser
用户 testuser 登录成功
Price history for ram/1865: 2 records
尝试认证: login_field=15631128911
认证成功: 用户 testuser
用户 testuser 登录成功
Price history for ram/1866: 2 records

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def check_price_changes():
    return 1

Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor

def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def check_price_changes():
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1

Using proactor: IocpProactor
Price history for ram/1866: 2 records
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def check_price_changes():
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor

def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def check_price_changes():
    return 1

Starting check_price_changes task
Processing favorite 73 for user 15631128911, component_type: ram
Item Test RAM: current_price=450.00, previous_price=480.00
Sending email for Test RAM to 1696995719@eqq.com
Email sent and notification recorded for Test RAM
Using proactor: IocpProactor
Using proactor: IocpProactor
Using proactor: IocpProactor
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Using proactor: IocpProactor
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
尝试认证: login_field=15631128911
认证成功: 用户 testuser
用户 testuser 登录成功
尝试认证: login_field=15631128911
认证成功: 用户 testuser
用户 testuser 登录成功
Price history for ram/1869: 2 records
Watching for file changes with StatReloader
Not Found: /favicon.ico
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /api/detail/ssd/1787/
Internal Server Error: /api/detail/ssd/1787/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Price history for ssd/1787: 4 records
Price history for ssd/1795: 2 records
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Price history for cpu/1: 4 records
Price history for cpu/8: 5 records
Price history for cpu/10: 3 records
Price history for cpu/19: 0 records
Price history for cpu/11: 2 records
尝试认证: login_field=entertainment33@qq.com
认证成功: 用户 entertainment33@qq.com
用户 entertainment33@qq.com 登录成功
Watching for file changes with StatReloader
Not Found: /favicon.ico
尝试认证: login_field=entertainment33@qq.com
认证成功: 用户 entertainment33@qq.com
用户 entertainment33@qq.com 登录成功
Watching for file changes with StatReloader
Not Found: /favicon.ico
尝试认证: login_field=root
认证成功: 用户 root
用户 root 登录成功
尝试认证: login_field=user
认证失败: 用户不存在 for user
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=textuser
认证失败: 用户不存在 for textuser
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=textuser
认证失败: 用户不存在 for textuser
登录失败: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>用户名、邮箱或手机与密码不匹配</li></ul></li></ul>
尝试认证: login_field=root
认证成功: 用户 root
用户 root 登录成功
Price history for cpu/1: 4 records
Price history for cpu/6: 10 records
Price history for cpu/6: 10 records
Price history for cpu/5: 1 records
Price history for cpu/1: 4 records
Price history for cpu/1: 4 records
尝试认证: login_field=15631128911
认证成功: 用户 testuser
用户 testuser 登录成功
Not Found: /favicon.ico
Price history for ram/1: 0 records
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /api/detail/motherboard/1/
Internal Server Error: /api/detail/motherboard/1/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Price history for motherboard/1: 2 records
Price history for motherboard/4: 1 records
Price history for motherboard/4: 1 records
Price history for motherboard/9: 0 records
Price history for motherboard/5: 5 records
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Price history for motherboard/4: 1 records
Price history for motherboard/9: 0 records
Price history for motherboard/10: 0 records
Price history for motherboard/1: 2 records
Price history for motherboard/2: 0 records
Price history for motherboard/9: 0 records
Price history for motherboard/3: 0 records
Price history for motherboard/2: 0 records
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Price history for motherboard/2: 0 records
Price history for motherboard/5: 5 records
Z:\desk\code\hardware_analyzer\analyzer\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/detail/gpu/1/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Price history for gpu/1: 1 records
Price history for gpu/8: 0 records
Price history for gpu/10: 3 records
Price history for gpu/7: 0 records
Price history for gpu/9: 0 records
Price history for gpu/7: 0 records
Price history for gpu/30: 5 records
Price history for gpu/29: 0 records
Price history for gpu/27: 0 records
Price history for gpu/25: 0 records
Price history for gpu/21: 3 records
Watching for file changes with StatReloader
Internal Server Error: /api/detail/power_supply/1/
Price history for ssd/1787: 4 records
Price history for ssd/1788: 0 records
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Price history for cooler/1: 0 records
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Detail error for case/1777: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1777/
Detail error for case/1780: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1780/
Detail error for case/1780: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1780/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Price history for gpu/1: 1 records
Price history for gpu/1: 1 records
Internal Server Error: /api/detail/power_supply/1/
Detail error for case/1777: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1777/
Price history for cooler/1: 0 records
Price history for cooler/3: 0 records
Watching for file changes with StatReloader
Detail error for case/1778: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1778/
Not Found: /favicon.ico
Detail error for case/1777: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1777/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/detail/case/1777/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Detail error for case/1777: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1777/
Detail error for case/1777: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1777/
Detail error for case/1784: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1784/
Detail error for case/1780: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1780/
Detail error for case/1780: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 206, in detail
    price_history = price_history_model.objects.filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'case' into field. Choices are: chassis, chassis_id, created_at, date, id, price
Internal Server Error: /api/detail/case/1780/
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Price history for chassis/1777: 0 records
Price history for chassis/1785: 0 records
Price history for chassis/1786: 0 records
Price history for chassis/1780: 0 records
Price history for chassis/1796: 1 records
Price history for chassis/1802: 0 records
Price history for chassis/1806: 0 records
Price history for chassis/1824: 0 records
Price history for chassis/1832: 0 records
Price history for chassis/1844: 0 records
Price history for chassis/1846: 1 records
Price history for chassis/1852: 0 records
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Error in average_price_trend: name 'FIELD_NAME_MAPPING' is not defined
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 348, in average_price_trend
    field_name = FIELD_NAME_MAPPING.get(component_type, component_type)
NameError: name 'FIELD_NAME_MAPPING' is not defined
Internal Server Error: /api/average_price_trend/
Error in average_price_trend: name 'FIELD_NAME_MAPPING' is not defined
Traceback (most recent call last):
  File "Z:\desk\code\hardware_analyzer\analyzer\views.py", line 348, in average_price_trend
    field_name = FIELD_NAME_MAPPING.get(component_type, component_type)
NameError: name 'FIELD_NAME_MAPPING' is not defined
Internal Server Error: /api/average_price_trend/
Price history for gpu/1: 1 records
Price history for gpu/6: 0 records
Price history for motherboard/1: 2 records
Price history for gpu/30: 5 records
Z:\desk\code\hardware_analyzer\analyzer\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/average_price_trend/
Z:\desk\code\hardware_analyzer\analyzer\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Price history for cpu/1: 4 records
Price history for cpu/2: 17 records
Price history for cpu/3: 10 records
Price history for cpu/4: 10 records
Price history for cpu/4: 10 records
Price history for cpu/7: 0 records
Price history for cpu/5: 1 records
Price history for cpu/1: 4 records
Price history for cpu/2: 17 records
Price history for cpu/4: 10 records
Watching for file changes with StatReloader
Not Found: /favicon.ico
Z:\desk\code\hardware_analyzer\analyzer\apps.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\hardware_analyzer\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Bad Request: /api/average_price_trend/
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Price history for gpu/1: 1 records
Price history for gpu/30: 5 records
Price history for gpu/30: 5 records
Price history for gpu/30: 5 records
Internal Server Error: /admin/analyzer/gpupricehistory/add/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1890, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1750, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1802, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1225, in save_model
    obj.save()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\base.py", line 897, in save_base
    post_save.send(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "Z:\desk\code\hardware_analyzer\analyzer\signals.py", line 36, in price_history_created
    for key, model in COMPONENT_PRICE_HISTORY_MODELS.items():
NameError: name 'COMPONENT_PRICE_HISTORY_MODELS' is not defined
Internal Server Error: /admin/analyzer/gpupricehistory/add/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1890, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1750, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1802, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\options.py", line 1225, in save_model
    obj.save()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\base.py", line 897, in save_base
    post_save.send(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "Z:\desk\code\hardware_analyzer\analyzer\signals.py", line 36, in price_history_created
    for key, model in COMPONENT_PRICE_HISTORY_MODELS.items():
NameError: name 'COMPONENT_PRICE_HISTORY_MODELS' is not defined
Internal Server Error: /admin/analyzer/cpupricehistory/
Traceback (most recent call last):
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 377, in date_hierarchy
    date_range = cl.queryset.aggregate(
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\query.py", line 605, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\query.py", line 549, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in apply_converters
    value = converter(value, expression, connection)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\db\backends\sqlite3\operations.py", line 324, in convert_datefield_value
    value = parse_date(value)
  File "Z:\anaconda3\envs\Django\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for gpu/30: 5 records
Price history for gpu/30: 5 records

def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def send_price_update_notification(user_id, component_type, component_id, component_title, current_price, previous_price, detail_url):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1

Connection to Redis lost: Retry (0/20) now.
Connection to Redis lost: Retry (1/20) in 1.00 second.
Connection to Redis lost: Retry (2/20) in 1.00 second.
Connection to Redis lost: Retry (3/20) in 1.00 second.
Connection to Redis lost: Retry (4/20) in 1.00 second.
Connection to Redis lost: Retry (5/20) in 1.00 second.
Connection to Redis lost: Retry (6/20) in 1.00 second.
Connection to Redis lost: Retry (7/20) in 1.00 second.
Connection to Redis lost: Retry (8/20) in 1.00 second.

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def send_price_update_notification(user_id, component_type, component_id, component_title, current_price, previous_price, detail_url):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def send_price_update_notification(user_id, component_type, component_id, component_title, current_price, previous_price, detail_url):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Watching for file changes with StatReloader

def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def send_price_update_notification(user_id, component_type, component_id, component_title, current_price, previous_price, detail_url):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1

Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for gpu/30: 5 records

def xmap(task, it):
    return 1


def send_price_update_notification(user_id, component_type, component_id, component_title, current_price, previous_price, detail_url):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def backend_cleanup():
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1

Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for cpu/1: 4 records
Price history for gpu/30: 6 records
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for gpu/30: 5 records
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for motherboard/1: 2 records
Price history for motherboard/2: 0 records
Notification sent to entertainment33@qq.com for 微星MAG B650M MORTAR WIFI
Price history for motherboard/2: 1 records
Price history for motherboard/2: 1 records
Not Found: /api/detail/
Not Found: /api/detail/
Z:\desk\code\hardware_analyzer\analyzer\signals.py changed, reloading.
Watching for file changes with StatReloader
Price history for motherboard/2: 1 records
